# Generated by Django 5.2.3 on 2026-07-01 22:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la clinique')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('wilaya', models.CharField(default='Alger', max_length=100, verbose_name='Wilaya')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('timezone', models.CharField(default='Africa/Algiers', max_length=50, verbose_name='Fuseau horaire')),
                ('subscription_tier', models.CharField(choices=[('free', 'Gratuit (Essai)'), ('starter', 'Starter'), ('pro', 'Pro')], default='free', max_length=20, verbose_name='Abonnement')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Clinique',
                'verbose_name_plural': 'Cliniques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('specialty', models.CharField(max_length=150, verbose_name='Spécialité')),
                ('resource_constraints', models.JSONField(blank=True, default=dict, help_text='Ex: {"room": "Salle 1", "requires_echo_machine": false}', verbose_name='Contraintes de ressources')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='providers', to='clinics.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Médecin / Praticien',
                'verbose_name_plural': 'Médecins / Praticiens',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ClinicStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('role', models.CharField(choices=[('owner', 'Propriétaire'), ('doctor', 'Médecin'), ('receptionist', 'Réceptionniste')], default='receptionist', max_length=20, verbose_name='Rôle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='clinics.clinic', verbose_name='Clinique')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_staff_profile', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('provider', models.OneToOneField(blank=True, help_text='Renseigné uniquement si ce compte correspond à un médecin de la clinique.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_account', to='clinics.provider', verbose_name='Médecin associé')),
            ],
            options={
                'verbose_name': 'Membre du personnel',
                'verbose_name_plural': 'Personnel',
                'ordering': ['clinic', 'role'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('name', models.CharField(help_text='Ex: "Consultation générale", "Échographie"', max_length=200, verbose_name='Nom du service')),
                ('average_duration', models.PositiveIntegerField(default=20, help_text='Durée moyenne estimée de la consultation en minutes.', verbose_name='Durée moyenne (minutes)')),
                ('price', models.DecimalField(decimal_places=2, help_text='Tarif de la consultation en Dinars Algériens.', max_digits=8, verbose_name='Prix (DZD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.provider', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Service / Consultation',
                'verbose_name_plural': 'Services / Consultations',
                'ordering': ['name'],
            },
        ),
    ]
