# Generated by Django 5.2.3 on 2026-07-01 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('scheduled_start', models.DateTimeField(verbose_name='Début prévu')),
                ('scheduled_end', models.DateTimeField(verbose_name='Fin prévue')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='Début réel')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='Fin réelle')),
                ('status', models.CharField(choices=[('scheduled', 'Planifié'), ('confirmed', 'Confirmé'), ('checked_in', 'Arrivé'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], db_index=True, default='scheduled', max_length=20, verbose_name='Statut')),
                ('no_show_probability', models.FloatField(blank=True, help_text="Calculé par le moteur d'optimisation. Valeur entre 0.0 et 1.0.", null=True, verbose_name="Probabilité d'absence")),
                ('lead_time_days', models.PositiveIntegerField(blank=True, help_text='Nombre de jours entre la réservation et le RDV.', null=True, verbose_name='Délai de réservation (jours)')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='Rappel envoyé')),
                ('reminder_acknowledged', models.BooleanField(default=False, help_text="True si le patient a répondu '1' pour confirmer.", verbose_name='Rappel confirmé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='patients.patient', verbose_name='Patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='clinics.provider', verbose_name='Médecin')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clinics.service', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Rendez-vous',
                'verbose_name_plural': 'Rendez-vous',
                'ordering': ['scheduled_start'],
                'indexes': [models.Index(fields=['scheduled_start', 'status'], name='scheduling__schedul_4ea709_idx'), models.Index(fields=['provider', 'scheduled_start'], name='scheduling__provide_7b5609_idx'), models.Index(fields=['patient', 'status'], name='scheduling__patient_340aa8_idx')],
            },
        ),
        migrations.CreateModel(
            name='SlotTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour de la semaine')),
                ('start_time', models.TimeField(verbose_name='Heure de début')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('default_slot_duration', models.PositiveIntegerField(default=20, verbose_name='Durée de créneau (minutes)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_templates', to='clinics.provider', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': 'Modèle de disponibilité',
                'verbose_name_plural': 'Modèles de disponibilité',
                'ordering': ['provider', 'day_of_week', 'start_time'],
                'unique_together': {('provider', 'day_of_week', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='WaitlistEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('preferred_slots', models.JSONField(blank=True, default=list, help_text='Ex: [{"day": "monday", "start": "09:00", "end": "12:00"}]', verbose_name='Créneaux préférés')),
                ('urgency', models.PositiveSmallIntegerField(default=1, help_text='1 = normal, 2 = prioritaire, 3 = urgent', verbose_name='Urgence')),
                ('priority_score', models.FloatField(db_index=True, default=0.0, verbose_name='Score de priorité')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('offered', 'Slot proposé'), ('accepted', 'Accepté'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], db_index=True, default='pending', max_length=20, verbose_name='Statut')),
                ('offer_made_at', models.DateTimeField(blank=True, null=True, verbose_name='Offre faite le')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='patients.patient', verbose_name='Patient')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_entries', to='clinics.provider', verbose_name='Médecin souhaité')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waitlist_entries', to='clinics.service', verbose_name='Service souhaité')),
            ],
            options={
                'verbose_name': "Liste d'attente",
                'verbose_name_plural': "Liste d'attente",
                'ordering': ['-priority_score', 'created_at'],
                'indexes': [models.Index(fields=['provider', 'status', '-priority_score'], name='scheduling__provide_d14563_idx')],
            },
        ),
    ]
