# Generated by Django 5.2.3 on 2026-07-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
        ('patients', '0002_patient_email'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'no_show']), _negated=True), fields=('provider', 'scheduled_start'), name='unique_active_appointment_slot'),
        ),
    ]
