# Generated by Django 5.2.3 on 2026-07-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_appointment_unique_active_appointment_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='delay_reason',
            field=models.CharField(blank=True, choices=[('late_arrival', 'Retard patient'), ('provider_overrun', 'Dépassement médecin'), ('room_unavailable', 'Salle indisponible'), ('admin_lag', 'Retard administratif'), ('other', 'Autre')], max_length=20, verbose_name='Cause du retard'),
        ),
        migrations.AddField(
            model_name='waitlistentry',
            name='offered_slot',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Créneau proposé'),
        ),
    ]
