# Generated by Django 5.2.3 on 2026-07-01 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('phone_number', models.CharField(help_text='Utilisé pour les rappels SMS/WhatsApp.', max_length=20, verbose_name='Numéro de téléphone')),
                ('date_of_birth', models.DateField(blank=True, help_text='Optionnel. Utilisé pour distinguer les patients homonymes.', null=True, verbose_name='Date de naissance')),
                ('clinic_ref', models.CharField(blank=True, help_text='Numéro de dossier interne de la clinique (optionnel).', max_length=50, verbose_name='Référence dossier')),
                ('notes', models.TextField(blank=True, help_text='Notes générales non-médicales (ex: préfère les rendez-vous matinaux).', verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic', verbose_name='Clinique')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('clinic', 'phone_number')},
            },
        ),
    ]
