# Generated by Django 5.2.3 on 2026-07-01 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, help_text='Optionnel. Utilisé pour les rappels par email (Phase 1, avant la passerelle SMS/WhatsApp).', max_length=254, verbose_name='Email'),
        ),
    ]
