# Generated by Django 5.2.3 on 2026-07-01 22:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptimizationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('run_type', models.CharField(choices=[('no_show_prediction', "Prédiction d'absence"), ('slot_allocation', 'Allocation des créneaux'), ('waitlist_matching', "Correspondance liste d'attente"), ('full_daily', 'Optimisation quotidienne complète')], max_length=30, verbose_name='Type de run')),
                ('run_status', models.CharField(choices=[('pending', 'En cours'), ('success', 'Succès'), ('partial', 'Partiel'), ('failed', 'Échec')], default='pending', max_length=20, verbose_name='Statut')),
                ('target_date', models.DateField(help_text='The clinic date this optimization run was computed for.', verbose_name='Date cible')),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Algorithm parameters used in this run (weights, solver timeout, etc.)', verbose_name='Paramètres')),
                ('results', models.JSONField(blank=True, default=dict, help_text='Output summary (e.g. predicted no-show count, solver objective value).', verbose_name='Résultats')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée (ms)')),
                ('provider', models.ForeignKey(help_text='Provider whose schedule was optimized in this run.', on_delete=django.db.models.deletion.CASCADE, related_name='optimization_runs', to='clinics.provider', verbose_name='Médecin')),
            ],
            options={
                'verbose_name': "Exécution d'optimisation",
                'verbose_name_plural': "Exécutions d'optimisation",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider', 'target_date', 'run_type'], name='optimizatio_provide_cdbc83_idx'), models.Index(fields=['run_status', '-created_at'], name='optimizatio_run_sta_bfaaba_idx')],
            },
        ),
    ]
